### ISSUE TITLE
Instructions on how to install from the source of this sbpl

### ISSUE THREAD

**Issue by abinashmeher999** [MASKOR/maskor_navigation#5]
So I saw this [question and answer](http://answers.ros.org/question/206703/sbpl_lattice_planner-loading-move_base-plugin-fails/) from ros answers.

> You can view a working version for indigo here: https://github.com/MASKOR/maskor_navi...
> 
> Make sure you use both the sbpl and sbpl_lattice_planner from source from that repo, as the normal sbpl does not link libraries correctly for sbpl_lattice_planner use

I uninstalled the debian package that I installed (`ros-indigo-sbpl`), to avoid any errors that could have been caused because of duplicates. And I followed the instructions from sbpl/sbpl repo to install this package. There were some errors. Then I tried to install by `catkin_make install --pkg sbpl` after realising it is a catkin_package. This shows the following error.

``` bash
abinashmeher999@JARVIS:~/agv$ catkin_make install --pkg sbpl
Base path: /home/abinashmeher999/agv
Source space: /home/abinashmeher999/agv/src
Build space: /home/abinashmeher999/agv/build
Devel space: /home/abinashmeher999/agv/devel
Install space: /home/abinashmeher999/agv/install
####
#### Running command: "make cmake_check_build_system" in "/home/abinashmeher999/agv/build"
####
####
#### Running command: "make install -j4 -l4" in "/home/abinashmeher999/agv/build/maskor_navigation/sbpl"
####
[100%] Built target sbpl
Install the project...
-- Install configuration: "Debug"
-- Installing: /home/abinashmeher999/agv/install/lib/pkgconfig/sbpl.pc
-- Installing: /home/abinashmeher999/agv/install/share/sbpl/cmake/sbplConfig.cmake
-- Installing: /home/abinashmeher999/agv/install/share/sbpl/cmake/sbplConfig-version.cmake
-- Installing: /home/abinashmeher999/agv/install/share/sbpl/package.xml
CMake Error at cmake_install.cmake:51 (FILE):
  file INSTALL cannot find
  "/home/abinashmeher999/agv/src/maskor_navigation/sbpl/InstallFiles/sbpl.pc".


make: *** [install] Error 1
Invoking "make install -j4 -l4" failed
```

Can you please give some clear instructions on what the answer meant.

**Comment by nlimpert** [comment]
The repo does not contain a valid install target.
Instead you can simply invoke a catkin_make in your workspace after cloning the maskor_navigation repo in the src folder.
The sbpl_lattice_planner then builds against the sbpl package and it works standalone.
The used sbpl package is basically just a clone of the sbpl/sbpl repo but there is no need to install it.
It's only there for the sbpl_lattice_planner.

**Comment by nlimpert** [comment]
Did that help you?
What are you trying to do?

**Comment by abinashmeher999** [comment]
Yes. Thanks for answering. I am facing other issues too, like SBPL Exceptions, due to unmatched resolutions. 
I am trying to get get a global planner that gives a pose associated global plan. So that planners like pose follower can get to work with that.

**Comment by nlimpert** [comment]
We had a similar issue with the resolution. The resolution in the motion primitive file has to match the resolution given by the costmap.
Have a look at https://github.com/MASKOR/maskor_navigation/blob/master/sbpl/matlab/mprim/rover_16.m - there's a resolution noted (0.05)
And then there's https://github.com/MASKOR/maskor_navigation/blob/master/sbpl_lattice_planner/launch/local_costmap_params_close.yaml which states that the costmap's resolution is also 0.05.

These are actual paramters we are using in a working environment.

You can also have a look at https://github.com/MASKOR/maskor_navigation/blob/master/sbpl_lattice_planner/launch/move_base_sbpl.launch - it's what launches the navigation for us (including sbpl_lattice_planner and pose_follower).

**Comment by abinashmeher999** [comment]
Oh I see. That might be the issue. I will try it out. Thanks a lot! :smile:
 Also I guess there aren't any zero radius turns in the motion primitives? I have a robot that has a minimum radius of turn. I plan to make some primitives myself. 
Will the current primitives work with a tricycle like robot?

**Comment by nlimpert** [comment]
Yes we are working with carlike robots here which can't turn in place.
The used primitives should work but you might want to tune the settings in pose_follower.cpp when you set up your own primitives as the current settings are made for our setup.
Mind if I close this issue then?
Feel free to ask further though ;)

You can also get in touch with us on gitter: https://gitter.im/MASKOR/maskor_navigation

**Comment by abinashmeher999** [comment]
Yes. Thank You. You can close the issue for now. I am already in the gitter chatroom. ;)
